Add MPICH build to docker container, drop ubuntu to 20.04

diff --git a/scripts/Dockerfile b/scripts/Dockerfile
--- a/scripts/Dockerfile
+++ b/scripts/Dockerfile
@@ -8,7 +8,9 @@
 #* Licensed under LGPL 2.1, please see LICENSE for details
 #* https://www.gnu.org/licenses/lgpl-2.1.html
 
-FROM ubuntu:22.04
+FROM ubuntu:20.04
+
+WORKDIR /opt
 
 # Add user dev
 RUN useradd -s /bin/bash dev
@@ -45,8 +47,7 @@ RUN apt-get update -y  && \
         sudo \
         update-motd \
         rsync \
-        cmake \
-        mpich
+        cmake
 
 # Clear package caches
 RUN rm -rf /var/lib/apt/lists/*
@@ -71,6 +72,39 @@ RUN pip3 --no-cache-dir install \
         pyyaml \
         scikit-image
 
+ENV MOOSE_JOBS=4
+
+# Install MPICH 4.0.2 to system path
+RUN curl -L -O https://www.mpich.org/static/downloads/4.0.2/mpich-4.0.2.tar.gz ; \
+tar -xf mpich-4.0.2.tar.gz ; \
+cd mpich-4.0.2 && mkdir gcc-build && cd gcc-build ; \
+# Configure build env
+../configure --prefix=/usr/local \
+--enable-shared \
+--enable-sharedlibs=gcc \
+--enable-fast=O2 \
+--enable-debuginfo \
+--enable-totalview \
+--with-device=ch3 \
+CC=gcc \
+CXX=g++ \
+FC=gfortran \
+F77=gfortran \
+F90='' \
+CFLAGS='' \
+CXXFLAGS='' \
+FFLAGS='' \
+FCFLAGS='' \
+F90FLAGS='' \
+F77FLAGS='' ; \
+# Build and install
+make -j ${MOOSE_JOBS} ; \
+make install ; \
+# Cleanup
+cd ../../ ; rm -rf mpich-4.0.2 ; \
+# Ensure mpich was installed by checking for binary
+if [ ! -f $(which mpicc) ]; then exit 1; fi
+
 # Set influential environment variables
 ENV CC=mpicc CXX=mpicxx
 
@@ -84,17 +118,17 @@ RUN git clone -b master https://github.com/shannon-lab/zapdos.git
 WORKDIR /home/dev/projects/zapdos
 RUN git submodule update --init
 
-ENV MOOSE_JOBS=6
+#ENV MOOSEDEV_REV=$(grep -oE "(\d+\.\d+\.\d+)" moose/conda/moose-dev/meta.yaml)
 
 # Build PETSc and libMesh using MOOSE scripts
 WORKDIR /home/dev/projects/zapdos/moose
-RUN ./scripts/update_and_rebuild_petsc.sh
+RUN ./scripts/update_and_rebuild_petsc.sh --download-cmake
 RUN ./scripts/update_and_rebuild_libmesh.sh
 RUN ./scripts/update_and_rebuild_wasp.sh
 
 # Make Zapdos
 WORKDIR /home/dev/projects/zapdos
-RUN make -j ${MOOSE_JOBS}
+RUN make -j 2
 RUN ./run_tests -j ${MOOSE_JOBS}
 
 # Make dev the owner of everything within its home directory to avoid permissions issues
